[package]
name = "plugin-server"
version = "0.0.0"
edition = "2021"

[dependencies]
rand = { version = "0.8", features = ["std", "std_rng"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
